version: '3.4'

services:
  dsslideshow:
    restart: always
    image: dsslideshow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment: 
      SECRET_KEY: 'insert_secret_key_here'