"""empty message

Revision ID: 6c7c9e0e87bc
Revises: 
Create Date: 2020-08-08 20:48:27.142753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7c9e0e87bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('path'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('content')
    # ### end Alembic commands ###
