name: docker-build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose up -d
      - name: Run
        run: docker run --network container:slideshow appropriate/curl -s --retry 10 --retry-connrefused http://localhost/